version: "1.0"
info:
  model: int-scaffold
packages:
- name: SerenGH1912Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareIBM
  gitUsername: ArtiKhareIBM
  gitBranch: main
- name: upperfspackage
  gitServerName: srcCtrl_bitbucket_Arti
  gitUrl: https://bitbucket.org/testartiibm
  gitUsername: artikhare
  gitBranch: master
